apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dialogos
  namespace: dialogos
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
    - host: dialogos.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dialogos
                port:
                  number: 80
